name: hello-world
on: push
jobs:
  Workflow_depen:
    uses: ./.github/workflows/Workflowdepen.yml
  my-job:
    runs-on: ubuntu-latest
    needs: [Workflow_depen]
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: Display Branch Name
        run: echo "Current Branch:${{ github.ref }}"
