name: hello-world
on: push
jobs:
  Workflow_depen:
    uses: ./.github/workflows/Workflowdepen.yml
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
